#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'sherlockAndAnagrams' function below.
#
# The function is expected to return an INTEGER.
# The function accepts STRING s as parameter.
#

from collections import Counter

def sherlockAndAnagrams(s):
    n=len(s)
    d={}
    for i in range(n):
        for j in range(1,n-i+1):
            x=frozenset(Counter(s[i:i+j]).items()) 
            d[x]=d.get(x,0)+1
    c=0
    for i in d:
        c+=d[i]*(d[i]-1)//2
    return c

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input().strip())

    for q_itr in range(q):
        s = input()

        result = sherlockAndAnagrams(s)

        fptr.write(str(result) + '\n')

    fptr.close()
